---
version: 0.8.0
theme: jekyll-theme-minimal
repository: "mbayopanda/inventory-tracker"
title: "Basic Hospital Information Management Application"
logo: "logo.png"
description: "Bhima is a free, open source accounting and hospital information management system (HIMS) tailored for rural hospitals in Africa. We are an international team based in the Democratic Republic of the Congo. BHIMA is an acronym for basic hospital information management application"
markdown: kramdown
sass:
  style: compressed
exclude:
  - .gitignore
  - .sass-cache
  - CNAME
  - Gemfile
  - Gemfile.lock
plugins:
  - "jekyll-github-metadata"
github: [metadata]
